[workspace]
members = [
	"rust_robotics_algo",
	"rust_robotics_sim",
	"examples",
]
exclude = [
	"python_interface"
]


# Required for wgpu v0.10 feature resolution.
resolver = "2"

[profile.release]
opt-level = 2 # fast and small wasm

[patch.crates-io]

